module Day2025_07

open Expecto
open Expecto.Flip

let sample = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

[<Tests>]
let tests =
    testList "Day 2025 07" [
        testCase "Part 1" <| fun _ ->
            Day2025_07.part1 sample
            |> Expect.equal "The expected value is " 21
        testCase "Part 2" <| fun _ ->
            Day2025_07.part2 sample
            |> Expect.equal "The expected value is " 40
    ]